before_install:
  - sudo apt-get update
  - sudo rm -f /etc/apt/sources.list.d/travis_ci_zeromq3-source.list
  - sudo apt-get install libzmq-dev libcurl4-openssl-dev arduino-core screen libboost-all-dev
  - sudo apt-get install doxygen graphviz
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

before_script:
  - sh utils/curlpp.sh

script:
  - mkdir build && cd build
  - cmake .. -DESSID="FAKEESSID" -DPASSWORD="FAKEPASSWORD" -DSERVER_IP="192.168.1.1" -DSERVER_PORT="80" -DBUILD_DOCUMENTATION=ON
  - make
  - make doc
  - timeout 20s ./examples/arduino/serial/mock/dmn_mock_serial
  - timeout 20s ./examples/arduino/temp_hum_server/mock/dmn_mock_server
