#!/bin/sh

DOMINUS_PREFIX="/usr/local/"
DOMINUS_ETC="$DOMINUS_PREFIX/etc/dominus"

if [ $# -eq 1 ]
then
    sudo ARDUINO_PORT=$1 screen -c $DOMINUS_ETC/monitor_screenrc
    sudo pkill dominus_monitor
else
    echo "ERROR: usage is ./dominus_monitor /dev/ttyX"
fi
